### ISSUE TITLE
the transfer does not work

### ISSUE THREAD

**Issue by chwanyoung** [johnfischelli/plugin-chat-sms-transfer#83]
after I click the transfer, the loading sign pop out. 
loading loading loading loading...................

It doesn't work.

**Comment by maxmito** [comment]
Do you have anything in the Twilio Error Logs in the Twilio console?Or in the browser logs?

**Comment by chwanyoung** [comment]
Thank you Max. I am a new dev.  How can I find twilit error logs?

Kind regards,

AP
On 30 Mar 2022, at 11:25 pm, Max ***@***.***> wrote:

﻿

Do you have anything in the Twilio Error Logs in the Twilio console?Or in the browser logs?

**Comment by maxmito** [comment]
You can find the Error Logs in your Twilio Console, under Monitor

**Comment by tsuandre** [comment]
@maxmito i'm facing the same error. 
I was about to open an issue when I found this one, i don't have error on error logs

**Comment by maxmito** [comment]
I also had issue at the beginning I kept troubleshooting by looking at errors on the Twilio Console and in the Browser Console.
Without providing any additional details it might be difficult for anyone to help you.
Try to get as much details and possibile and post it here

**Comment by tsuandre** [comment]
Is there a way to see the twilio console logs? I already activate the live logs option, but nothing is shown when the plugin is tested

**Comment by chwanyoung** [comment]
![image](https://user-images.githubusercontent.com/40587392/160935033-d5bb4496-98a7-45ca-897b-bc35ccae758a.png)

**Comment by chwanyoung** [comment]
thanks everyone. 
and here is my second task queue settings (first is the default queue called everyone)
![image](https://user-images.githubusercontent.com/40587392/160935454-ff3401a1-6477-49f0-aa8a-9811747add3f.png)

**Comment by chwanyoung** [comment]
and here is the chat transfer workflow
![image](https://user-images.githubusercontent.com/40587392/160938626-b8d098b2-a27e-497e-9f78-40ba3581ac97.png)

**Comment by johnfischelli** [comment]
Hello,

I wrote the original implementation of this plugin so I'm sure I can help here.

You mentioned you click the "Transfer" button in the UI and that the "loading sign pops out" - but I'm not sure what this means. Can you show a screenshot of this?

Clicking the transfer button invokes a Flex Action: https://github.com/twilio-professional-services/plugin-chat-sms-transfer/blob/main/src/components/TransferButton/index.js#L12

This action simply reveals a built-in UI native to Flex to list out Queues or Workers to transfer the task to. https://www.twilio.com/docs/flex/developer/ui/components#workerdirectory 

If that was loading forever, then you never even got a chance to attempt a transfer and there is likely something else wrong.

Secondly, this plugin initiates an HTTP request to a Twilio function to perform the actual transfer logic. If you are successfully seeing this request initiate, but it is failing please attach a screenshot of the browser console logs so we can determine why.

**Comment by chwanyoung** [comment]
thanks johnfischelli,
Sorry, My mistake. 
The loading sign is not in the pop-up.

After I click on the transfer button, this pops out
![image](https://user-images.githubusercontent.com/40587392/160953435-0b67bcb8-e1fd-443f-8e11-3d96b54c4c95.png)
I then clicked on the arrow, 
![image](https://user-images.githubusercontent.com/40587392/160953544-196a4868-06a4-47df-9f45-83c7189ff279.png)
something is wrong here.

Any ideas? 
Cheers,
AP

**Comment by chwanyoung** [comment]
Hi Everyone, 

found the issue

The plugin source code from this [link](https://www.twilio.com/docs/flex/solutions-library/chat-and-sms-transfers) is outdated. You need to upgrade it. For example replacing public/appConfig.example.js with public/appConfig.js

The windows command that creates the TaskRouter workflow has the single quotation marks ('task.targetSid') which needs to be removed (task.targetSid) 

Hope it helps.

AP
